# Site Settings
lang: en
title: Simone Precicchiani
tagline: tagline
email: simone.precicchiani@gmail.com
description: >
  description
baseurl: ""
url: ""
permalink: pretty
website: "simoneprecicchiani.com"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - .gitignore

sass:
  style: compressed
  source_dir: _sass

markdown: kramdown
highlighter: rouge